version: '3'

services:
  server:
    container_name: NODEJS_SERVER
    build: '.'
    volumes:
      - ./:/api-login
      - ./node_modules:/api-login/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    command: sh -c "yarn start"

  db:
    image: 'mongo'
    container_name: MONGODB
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db