type User {
  email: String!
  password: String!
  name: String!
}

input UserInput {
  email: String!
  password: String!
  name: String!
}

type Query {
  user(email: String!): User!
  recoverPassword(email: String!, name: String!): User!
  login(email: String!, password: String!): User!
  tryLogin(email: String!, password: String!): Boolean
}

type Mutation {
  createUser(data: UserInput!): User!
  updateUser(data: UserInput!): User!
  deleteUser(email: String!): Boolean
}
